[package]
name = "core-affinity"
version = "0.1.0"
authors = ["jethrosun <jethro.rules@real.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core_affinity = "*"
